names =[ 'danial', 'amirhosein', 'shayan', 'pitt','mohammad','arsam','reza','sina', 'amir', 'mohsen']
print(names[0])
print(names[1].title())
print(names[2].upper())
print(names[3].lower())
print(names[4])
print(names[-5].lower())
print(names[-4].title())
print(names[-3].upper())
print(names[-2])
print(names[-1].upper())